### ISSUE TITLE
Add an option to set draft pod size?

### ISSUE THREAD

**Issue by scottchiefbaker** [danieljbrooks/draftsim-launch#10]
How many bots are currently in the draft? Is there a way to configure this?

**Comment by danieljbrooks** [comment]
This is specified in the drafting.js file

 "function Draft(s1, s2, s3, n_players){
  num_players=n_players; //make global variable"

Note that sealed is considered a "1-player" draft

 "function Sealed_ORI(){
  draft = new Draft(ORI, ORI, ORI, 1);"

I've only tested 1 and 8 players drafts, you may need to check the other
numbers

**Comment by danieljbrooks** [comment]
Draft(ORI,ORI,ORI, 6) //6 player ORI draft
