### ISSUE TITLE
License

### ISSUE THREAD

**Issue by arxanas** [danieljbrooks/draftsim-launch#19]
Are you planning to license the code? As cool as the project is, I don't think I can be consistent with my ideals and also keep working on it.

**Comment by danieljbrooks** [comment]
Do you prefer a totally open source license? We could do that.

Appreciate your contributions

-Dan

**Comment by arxanas** [comment]
I'm not picky about how open the license is, just that there's actually a license in place so that people can make use of it. (What are the rules about using unlicensed code? I think one can't use it at all.) GPL to WTFPL are all fine by me.

**Comment by danieljbrooks** [comment]
Updated to license.txt to GNU public license:
This software is available for public use. Please direct inquiries and
comments to: email.draftsim@gmail.com License: This program is free
software: you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
more details. You should have received a copy of the GNU General Public
License along with this program. If not, see <http://www.gnu.org/licenses/>.
