### ISSUE TITLE
Can't see reverse side of double-faced cards in draft or sealed pool

### ISSUE THREAD

**Issue by demern** [danieljbrooks/draftsim-launch#29]
As the title mentions, there is no way to see the reverse side of double-faced cards in your pool. You can hover over cards to see an enlarged image of the front, but the back is inaccessible. This can make deckbuilding difficult in sets (like Innistrad: Midnight Hunt) that include lots of double-faced cards. My hope was that something could be added to make this information accessible. Either (1) being able to toggle which side is shown by holding down a key, or (2) displaying front/back next to each other when you hover over a card.

**Comment by danieljbrooks** [comment]
Thanks for reaching out. 

This repo has the original draftsim source code and is no longer supported. 

For the live website, reach out to Dan Troha on via the link here: https://draftsim.com/contact/

**Comment by demern** [comment]
Thank you for the quick response! Unfortunately, the 'contact' form on the site doesn't seem to work. I can fill out all the boxes, but don't see a "submit" button (using Chrome 93.0.4577.63 w/ adblock disabled). In any case, if the latest code is open source still, do you have a link to that? Would be happy to poke around and try it myself if you're open to outside contributions.

-Nick

**Comment by danieljbrooks** [comment]
Great point! I'm not seeing the submit either. Try emailing dan (at) draftsim.com. You should get a response pretty fast.
