### ISSUE TITLE
Improved Sorting

### ISSUE THREAD

**Issue by danieljbrooks** [danieljbrooks/draftsim-launch#7]
The current implementation sorts by curve and color. We want to sort by curve, color, and alphabetically. That can be done using:
http://www.growingwiththeweb.com/2014/07/order-a-js-array-by-multiple-properties.html

Second, implement more sort options for deckbuilding (curve, color, etc.)

**Comment by danieljbrooks** [comment]
Implemented alphabetical curving (now live)

**Comment by danieljbrooks** [comment]
And color sorting implemented for draft. closed.

**Comment by scottchiefbaker** [comment]
What's alphabetical curving?

**Comment by danieljbrooks** [comment]
The current sorting method sorts by 4 parameters:

-colorsort (color)
-creaturesort (creature, noncreature, land)
-cmc
-name

Adding the name as a tiebreaker makes the sorting order deterministic and
ensures that multiples of a card are adjacent

**Comment by scottchiefbaker** [comment]
So this is purely to affect how it draws on the screen?

**Comment by danieljbrooks** [comment]
Yes. The cards in the player's deck and collection are now sorted in a more
logical way
