### ISSUE TITLE
Pack Color Distribution

### ISSUE THREAD

**Issue by danieljbrooks** [danieljbrooks/draftsim-launch#8]
The packs are currently randomly generated. Real packs use print runs. We'd like the color/card distribution between these two to be similar. We'd also like a maintainable solution for future sets. 

For reference, info on Origins pick orders are here: https://www.reddit.com/r/lrcast/comments/3dkr40/magic_origins_anatomy_of_a_booster_pack_common/

A basic solution would be to limit common generation to between 1 and 3 cards of each color per pack. 

Also, people seem to think that there are more multiples of rares on the simulator than there are in live drafts due to print runs. Perhaps the frequency of repeat rares/mythics can be reduced.

**Comment by danieljbrooks** [comment]
Implemented 1-3 commons per color. Resolved.

**Comment by scottchiefbaker** [comment]
How do you handle artifacts/gold cards?

**Comment by danieljbrooks** [comment]
The algorithm is:

Generate a random common
-If it's a duplicate common, generate a new one
-If you have three commons of that color (mono-colored), generate a new one
-If there are N commons left and N WUBRG colors not represented, generate a
common of each of those colors

**Comment by scottchiefbaker** [comment]
Not to beat a dead horse but...

With this logic it's possible to have a pack with 5 cards of the same color? Rare, Uncommon, three commons? I don't think this happens in the cardboard world.

Is there any logic about the uncommon color distribution?
